# TCL File Generated by Component Editor 18.1
# Wed Jun 26 19:00:54 ART 2019
# DO NOT MODIFY


# 
# EV19_Core "EV19_Core" v1.0
#  2019.06.26.19:00:54
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module EV19_Core
# 
set_module_property DESCRIPTION ""
set_module_property NAME EV19_Core
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME EV19_Core
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Core
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file FePipelineReg.vhd VHDL PATH Bloques/Fetch/FePipelineReg.vhd
add_fileset_file ResetPC.vhd VHDL PATH Bloques/Fetch/ResetPC.vhd
add_fileset_file ControlStore.vhd VHDL PATH Bloques/Decode/ControlStore.vhd
add_fileset_file DePipelineReg.vhd VHDL PATH Bloques/Decode/DePipelineReg.vhd
add_fileset_file InstDecoder.vhd VHDL PATH Bloques/Decode/InstDecoder.vhd
add_fileset_file RegisterFile.vhd VHDL PATH Bloques/Decode/RegisterFile.vhd
add_fileset_file immGenerator.vhd VHDL PATH Bloques/Decode/immGenerator.vhd
add_fileset_file ALU_ExtendBit.vhd VHDL PATH Bloques/Execute/ALU_ExtendBit.vhd
add_fileset_file ALU_Logic.vhd VHDL PATH Bloques/Execute/ALU_Logic.vhd
add_fileset_file ByteEnableBlock.vhd VHDL PATH Bloques/Execute/ByteEnableBlock.vhd
add_fileset_file ExPipelineReg.vhd VHDL PATH Bloques/Execute/ExPipelineReg.vhd
add_fileset_file ShiftBlock.vhd VHDL PATH Bloques/Execute/ShiftBlock.vhd
add_fileset_file MePipelineReg.vhd VHDL PATH Bloques/Memory/MePipelineReg.vhd
add_fileset_file EV19_Constants.vhd VHDL PATH Bloques/EV19_Constants.vhd
add_fileset_file EV19_ISA.vhd VHDL PATH Bloques/EV19_ISA.vhd
add_fileset_file EV19_Types.vhd VHDL PATH Bloques/EV19_Types.vhd
add_fileset_file ForwardingHazardUnit.vhd VHDL PATH Bloques/ForwardingHazardUnit.vhd
add_fileset_file Core.vhd VHDL PATH Bloques/VHDL(simulacion)/Core.vhd TOP_LEVEL_FILE
add_fileset_file Decode.vhd VHDL PATH Bloques/VHDL(simulacion)/Decode.vhd
add_fileset_file Execute.vhd VHDL PATH Bloques/VHDL(simulacion)/Execute.vhd
add_fileset_file ExecuteALU.vhd VHDL PATH Bloques/VHDL(simulacion)/ExecuteALU.vhd
add_fileset_file ExecuteBranch.vhd VHDL PATH Bloques/VHDL(simulacion)/ExecuteBranch.vhd
add_fileset_file Fetch.vhd VHDL PATH Bloques/VHDL(simulacion)/Fetch.vhd
add_fileset_file LoadBlock.vhd VHDL PATH Bloques/VHDL(simulacion)/LoadBlock.vhd
add_fileset_file LongInstruction.vhd VHDL PATH Bloques/VHDL(simulacion)/LongInstruction.vhd
add_fileset_file Memory.vhd VHDL PATH Bloques/VHDL(simulacion)/Memory.vhd
add_fileset_file Writeback.vhd VHDL PATH Bloques/VHDL(simulacion)/Writeback.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point Data_Master
# 
add_interface Data_Master avalon start
set_interface_property Data_Master addressUnits SYMBOLS
set_interface_property Data_Master associatedClock clock
set_interface_property Data_Master associatedReset reset
set_interface_property Data_Master bitsPerSymbol 8
set_interface_property Data_Master burstOnBurstBoundariesOnly false
set_interface_property Data_Master burstcountUnits WORDS
set_interface_property Data_Master doStreamReads false
set_interface_property Data_Master doStreamWrites false
set_interface_property Data_Master holdTime 0
set_interface_property Data_Master linewrapBursts false
set_interface_property Data_Master maximumPendingReadTransactions 0
set_interface_property Data_Master maximumPendingWriteTransactions 0
set_interface_property Data_Master readLatency 0
set_interface_property Data_Master readWaitTime 1
set_interface_property Data_Master setupTime 0
set_interface_property Data_Master timingUnits Cycles
set_interface_property Data_Master writeWaitTime 0
set_interface_property Data_Master ENABLED true
set_interface_property Data_Master EXPORT_OF ""
set_interface_property Data_Master PORT_NAME_MAP ""
set_interface_property Data_Master CMSIS_SVD_VARIABLES ""
set_interface_property Data_Master SVD_ADDRESS_GROUP ""

add_interface_port Data_Master dataMemAddress address Output 32
add_interface_port Data_Master dataMemByteEnable byteenable Output 4
add_interface_port Data_Master dataMemReadData readdata Input 32
add_interface_port Data_Master dataMemReadReq read Output 1
add_interface_port Data_Master dataMemWaitReq waitrequest Input 1
add_interface_port Data_Master dataMemWriteData writedata Output 32
add_interface_port Data_Master dataMemWriteReq write Output 1


# 
# connection point Instruction_Master
# 
add_interface Instruction_Master avalon start
set_interface_property Instruction_Master addressUnits SYMBOLS
set_interface_property Instruction_Master associatedClock clock
set_interface_property Instruction_Master associatedReset reset
set_interface_property Instruction_Master bitsPerSymbol 8
set_interface_property Instruction_Master burstOnBurstBoundariesOnly false
set_interface_property Instruction_Master burstcountUnits WORDS
set_interface_property Instruction_Master doStreamReads false
set_interface_property Instruction_Master doStreamWrites false
set_interface_property Instruction_Master holdTime 0
set_interface_property Instruction_Master linewrapBursts false
set_interface_property Instruction_Master maximumPendingReadTransactions 0
set_interface_property Instruction_Master maximumPendingWriteTransactions 0
set_interface_property Instruction_Master readLatency 0
set_interface_property Instruction_Master readWaitTime 1
set_interface_property Instruction_Master setupTime 0
set_interface_property Instruction_Master timingUnits Cycles
set_interface_property Instruction_Master writeWaitTime 0
set_interface_property Instruction_Master ENABLED true
set_interface_property Instruction_Master EXPORT_OF ""
set_interface_property Instruction_Master PORT_NAME_MAP ""
set_interface_property Instruction_Master CMSIS_SVD_VARIABLES ""
set_interface_property Instruction_Master SVD_ADDRESS_GROUP ""

add_interface_port Instruction_Master instMemWaitReq waitrequest Input 1
add_interface_port Instruction_Master instMemReadData readdata Input 32
add_interface_port Instruction_Master instMemReadReq read Output 1
add_interface_port Instruction_Master instMemByteEnable byteenable Output 4
add_interface_port Instruction_Master instMemAddress address Output 32


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point enablePredictor
# 
add_interface enablePredictor conduit end
set_interface_property enablePredictor associatedClock ""
set_interface_property enablePredictor associatedReset ""
set_interface_property enablePredictor ENABLED true
set_interface_property enablePredictor EXPORT_OF ""
set_interface_property enablePredictor PORT_NAME_MAP ""
set_interface_property enablePredictor CMSIS_SVD_VARIABLES ""
set_interface_property enablePredictor SVD_ADDRESS_GROUP ""

add_interface_port enablePredictor enablePredictor config Input 1

